#!/bin/sh

set -e

QTUM_NETWORK=${QTUM_NETWORK:-"regtest"}

case $QTUM_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $QTUM_NETWORK"
    exit 1
esac

mkdir -p $QTUM_DATADIR
QTUM_DEBUG=${QTUM_DEBUG:0}

exec qtumd ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:13889 -rpcallowip=192.168.0.0/16 \
  -datadir=$QTUM_DATADIR \
  -logevents \
  -logips \
  -debug=$QTUM_DEBUG \
  -rpcuser=$QTUM_RPC_USER -rpcpassword=$QTUM_RPC_PASS \
  -printtoconsole
